### ISSUE TITLE
No error output from torq.sh 

### ISSUE THREAD

**Issue by Aqualex** [AquaQAnalytics/TorQ#113]
There are no error messages from the torq.sh script when something is not working. Adding a log file where the torq.sh can print errors and usage messages could be beneficial in debugging it.

**Comment by jonathonmcmurray** [comment]
Can you give an example of the type of thing that is not working?

**Comment by Aqualex** [comment]
I am trying start the Torq-FX using torq.sh. It seems to read the process.csv, but does not start any process. I am trying to debug torq.sh right now, but it would be really helpful if when I execute it instead of giving me this: 

```arisnoveanu@homer:~/alexeiDev/torqfx/deploy$
arisnoveanu@homer:~/alexeiDev/torqfx/deploy$ ./torq.sh start all
arisnoveanu@homer:~/alexeiDev/torqfx/deploy$```

it would give me at least an idea where it breaks or why it doesn't start any processes.

**Comment by jonathonmcmurray** [comment]
I agree that enhanced logging would be good. I think in that case though it's likely due to the process.csv not being updated in TorQ-FX package with the extra fields now used by new start script

**Comment by ThomasSmyth** [comment]
Might be worth opening that issue in the FX repo.

**Comment by Aqualex** [comment]
I modified the process.csv for my case ... well his case. It works well. We could open the issue both in TorQ-FX and TorQ-GDAX to make them work with the new torq.sh script. I had some questions from people why ./torq.sh summary doesn't work when they use ./startFX.sh and ./startGDAX.sh
