### ISSUE TITLE
upd default

### ISSUE THREAD

**Issue by frenzy21** [AquaQAnalytics/TorQ#118]
23  upd:{{[t;x] insert[t;x]}}               // default upd function used for replaying data 

\Is this nested function as a default ok?

**Comment by frenzy21** [comment]
realupd:{[f;t;x]  
228  	// increment the tablecounts 
229          tablecounts[t]+::count first x; 
230  	// run the supplied function in the error trap 
231  	.[f;(t;x);{[t;x;e] errorcounts[t]+::count first x}[t;x]]; 
232  	}[.replay.upd] 

The function needs unnested essentially here or am I misisng something?

[ Note Im confused as this defo used to work fine. ]

**Comment by jonnypress** [comment]
Nested function: probably ok. We could probably lose the nesting and just set to insert, I think the fact it's in a function adds in the region of 100-200 ns to each invocation e.g. comparing 

q)\ts:1000000 10+20                                                                                                                                        
246 608
q)\ts:1000000 {x+y}[10;20]                                                                                                                                 
371 1120

125 ns per invocation of second version

And to be clear - assuming you are talking about this line: 
https://github.com/AquaQAnalytics/TorQ/blob/master/code/processes/tickerlogreplay.q#L22
then the definition of upd will end up being 
{[t;x] insert[t;x]}

r.e. second question - not sure.  What's happening?  That bit looks ok to me (in isolation at least)

**Comment by frenzy21** [comment]
This is giving me a rank error as it stands. Ill look to see if its soemthing silly Im doing.
