### ISSUE TITLE
.servers.opencon does not use username or password for other ipctype

### ISSUE THREAD

**Issue by sitsang** [AquaQAnalytics/TorQ#133]
in [trackservers.q](../blob/master/code/handlers/trackservers.q#L54), opencon is checking the connection by checking the number of colon:

```
        connection:hsym $[2 >= sum ":"=string x; `$(string x),":",string USERPASS^PASSWORDS[x];x];
```

but when the connection type is tcps, this will not work.  The next line is also problematic for tcps:

```
h:@[{(hopen x;"")};(connection;.servers.HOPENTIMEOUT);{(0Ni;x)}];
```
timeout is not supported for tcps, so hopen would fail.

**Comment by liammcgrenaghan** [comment]
Hi sitsang,

We're are looking into this issue at the moment and will be back to you as soon as possible.

Regards
Liam at AquaQ Analytics
