### ISSUE TITLE
Win x64 email error

### ISSUE THREAD

**Issue by ioiopp** [AquaQAnalytics/TorQ#153]
May I know if email function has been tested on Win 10 x64? As soon as I change "enabled" for 1b in settings\default.q, start_torq_demo.bat wont execute correctly and processes are not starting. Other configs are the same. Thanks.

**Comment by GSaunders92** [comment]
Hi there. Unfortunately the email functionality is not supported for Windows 64bit. We will modify our logging to make this more clear. Sorry for the inconvenience.
