### ISSUE TITLE
Possible to violate .readonly property via gateway functions

### ISSUE THREAD

**Issue by SMLaursen** [AquaQAnalytics/TorQ#162]
We're in the process of amending our existing KDB setup with TorQ. Initially we just want to prevent accidental deletions and modifications to existing data where **writeaccess.q** appears more suitable than using the fullblown permission setup

I've enabled the readonly parameter on **default.q** (i.e. every process) and as expected i get a \`noupdate error when I try to modify the tables from either the gateway or rdb. But I've noticed that connecting to the gateway and issuing e.g. h(\`.gw.syncexec;"delete from orders";\`rdb) executes thereby violating the readonly setting.

Win10, KDB 3.6 (32bit) and TorQ 3.5.0

**Comment by jwrno1** [comment]
Hi SMLaursen,

We're currently looking into a suitable fix for this, we'll get back to you when we have one. 

Regards,
Josh at AquaQ
