### ISSUE TITLE
Housekeeping zip function maps to rm on windows

### ISSUE THREAD

**Issue by SMLaursen** [AquaQAnalytics/TorQ#164]
On windows, specifying a zip housekeeping function will lead to a deletion;

**housekeeping.q**:l126
`
$[.z.o like "w*";[find:.win.find; rm:.win.rm;zip:.win.rm;];[find:.unix.find; rm:.unix.rm;zip:.unix.zip;]]
`

**Comment by ThomasSmyth** [comment]
Addressed by #165.
