### ISSUE TITLE
Gateway can get "stuck" if process being queried hits a 'stop error

### ISSUE THREAD

**Issue by jonnypress** [AquaQAnalytics/TorQ#242]
Gateway sends requests to other processes. If the processes have a timeout (-T) set then if the query runs for too long the it will hit a 'stop and not return anything to the gateway. All other types of error are trapped and an return ensured, but I don't think there's a way to do this for 'stop error. 

Instead, I think we need something to periodically check the status of long running requests. The current server list is stored in .gw.servers, the query to find long running requests (which may have failed) would be 

select from .gw.servers where inuse, lastquery<.proc.cp[] - 0D00:01

(where 0D00:01 is a configurable period)

If any processes match this criteria, then the gateway should send those processes an async request to respond back and update their status to 0b. The problem above is basically that upon a stop error the active flag is stuck at 1b, and if there is only a single instance of this proctype available it means all future queries timeout.

**Comment by robsketch** [comment]
It seems when I replicate the issue that the stop error is trapped and returned the the gateway.  I set -T to be 1 in process.csv for the hdb and ran a query which takes a couple of seconds and get the following output:

```
q)neg[h](`.gw.asyncexec;"select from quote";`hdb);h[]
"error: failed to run query on server rob:6003: stop"
q)h".gw.servers"
serverid| handle servertype inuse active querycount lastquery                ..
--------| -------------------------------------------------------------------..
1       | 6      rdb        0     1      0                                   ..
2       | 7      hdb        0     1      18         2020.03.16D14:06:18.04591..
3       | 8      hdb        0     1      0                                   ..
```

So it seems that the error is caught and returned to the gateway and the inuse value is updated to 0?

**Comment by robsketch** [comment]
Testing with a longer timeout:

```
q)neg[h](`.gw.asyncexec;"{0b} {x+1}/[1]";`hdb);h[]
"error: failed to run query on server rob:6003: stop"
q)h".gw.servers"
serverid| handle servertype inuse active querycount lastquery                ..
--------| -------------------------------------------------------------------..
1       | 6      hdb        0     1      1          2020.03.16D16:47:51.97004..
2       | 7      hdb        0     1      0                                   ..
3       | 14     rdb        0     1      0                                   ..
```

Increased the timeout to 1 minute and stop error is still trapped.

**Comment by robsketch** [comment]
Tried to see if the problem occurs when the client disconnects, but the `'stop` error is still caught at timeout and `inuse` is updated to `0`.

```
q)neg[h](`.gw.asyncexec;"{0b} {x+1}/[1]";`hdb);h[]
'rcv handle: 4. OS reports: Interrupted system call
  [0]  neg[h](`.gw.asyncexec;"{0b} {x+1}/[1]";`hdb);h[]
                                                    ^
q)h:hopen`::6007:admin:admin
q)h".gw.servers"
serverid| handle servertype inuse active querycount lastquery                ..
--------| -------------------------------------------------------------------..
1       | 6      rdb        0     1      0                                   ..
2       | 7      hdb        1     1      8          2020.03.17D15:15:13.62977..
3       | 8      hdb        0     1      0                                   ..
q)'stop
  [0]  error: failed to run query on server rob:6003: stop
                                                      ^
q)h".gw.servers"
serverid| handle servertype inuse active querycount lastquery                ..
--------| -------------------------------------------------------------------..
1       | 6      rdb        0     1      0                                   ..
2       | 7      hdb        0     1      8          2020.03.17D15:15:13.62977..
3       | 8      hdb        0     1      0                                   ..
```

So it does not appear to be a problem.
