### ISSUE TITLE
./torq.sh stop all - kill command fails

### ISSUE THREAD

**Issue by hoont** [AquaQAnalytics/TorQ#257]
When running `./torq.sh stop all` or any variation of `./torq.sh stop`, the following error is output for each running process:
`kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`
checking the status using `summary` shows the processes are still running.

From what I can see this is originating from line 142 in `torq.sh` - debugging the kill command shows there is no output from `lsof -i :$port -sTCP:LISTEN | awk '{if(NR>1)print $2}'`

This is failing because the line above:
`port=$(($(eval echo \$"$(getfield "$procno" port)")))`
seems to truncate the value of the port number. I'm not sure whether `getfield` is causing this when pulling from the config or not.

My appconfig/process.csv is very basic:
```
host,port,proctype,procname,U,localtime,g,T,w,load,startwithall,extras,qcmd
testhost,9998,tickerplant,tp_1,,1,1,3,,,1,,q
testhost,9997,rdb,rdb_1,,1,1,60,4000,,1,,q
testhost,9996,hdb,hdb_1,,1,1,60,4000,,1,,q
```

Adding an `echo $port` and running `./torq.sh stop all` with processes running outputs the following:
```
00:09:32 | Shutting down tp_1...
998
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
00:09:32 | Shutting down rdb_1...
997
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
00:09:32 | Shutting down hdb_1...
996
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

I'm running 64 bit Kubuntu 18.04.4 and bash 4.4.20

Is this something I'm doing wrong?

**Comment by InDeNiall104** [comment]
Thank you contacting us about this issue, I hopefully have a fix for it.
Please see this PR #264
