### ISSUE TITLE
tickerlogreplay bug fails to create empty table

### ISSUE THREAD

**Issue by MrListerCoUk** [AquaQAnalytics/TorQ#349]
_createemptytable_ call to _savetabdatatrapped_ missing final param so empty table doesn't ever get created
should be updated to
`savetabdatatrapped[h;p;t;0#value t;0b;td]`

**Comment by etennoQ** [comment]
Hi,

Thank you for making us aware of the issues and the suggested solutions, both for this issue and #350.

All should be sorted now

Kindest regards
Elliot
