### ISSUE TITLE
createalias does not support Windows

### ISSUE THREAD

**Issue by FlyingOE** [AquaQAnalytics/TorQ#364]
createalias works only in *nix environment. need to add support for Windows using "mklink /h"

**Comment by andrew-west** [comment]
Hi @FlyingOE,

Thanks for this. 

I've added a [suggestion](https://github.com/FlyingOE/TorQ/commit/81bf422c811a15396f5a411d392eeb89de175c1f) under the last commit to first try and create a symbolic link and then create a hard link if that fails.

Can you review and if you're happy, commit the change and create a pull request into TorQ? I'll then review and accept it.

Thanks
Andrew

**Comment by andrew-west** [comment]
I've approved and merged your pull request, thanks!
