### ISSUE TITLE
can't  subscribe  to only one segmented ticker plant 

### ISSUE THREAD

**Issue by Igor-Mochalin** [AquaQAnalytics/TorQ#374]
I have 2 segmented tps (stp1,stp2) and one segmentedchainedtickerplant (sctp)
I would like to subscribe to  stp1 from sctp ( i used **sctp.tickerplantname**)
I have the following  configuration:
```
localhost,{KDBBASEPORT}+1,segmentedtickerplant,stp1.....
localhost,{KDBBASEPORT}+2,segmentedtickerplant,stp2.....
localhost,{KDBBASEPORT}+25,segmentedchainedtickerplant,sctp .....    -.sctp.tickerplantname stp1
```
connect to segmentedchainedtickerplant -> .z.W and  i see open handles for stp1 and stp2 instead of stp1 only

**Comment by etennoQ** [comment]
Hi @Igor-Mochalin 

Thank you for raising this issue.

This behaviour shouldn't cause any problems. The SCTP connects to any process of type segmentedtickerplant by default so both sets of handles should appear in .z.W. However, the SCTP only subscribes to the name that you have given. So with your config, the subscription should be correct.

You can double check the subscription by checking that .stpps.subrequestall in stp2 does NOT contain any handles to the SCTP (and vice versa for stp1). Please let us know if this is not that case.

Kindest regards
Support team

**Comment by Igor-Mochalin** [comment]
Thanks for quick reply!
> The SCTP connects to any process of type segmentedtickerplant by default so both sets of handles should appear in .z.W

Hm ..  it's strange behavior , any reason for that ?

> You can double check the subscription by checking that .stpps.subrequestall in stp2 does NOT contain any handles to the SCTP (and vice versa for stp1

Yes,  looks ok! Thanks a lot!

**Comment by etennoQ** [comment]
I dont believe there is a specific reason for this other than the fact that the SCTP uses the .servers.CONNECTIONS list to control process connections, which is standard in TorQ. 

Glad to hear its working. If there are any other issues, please let us know.

Kindest regards
Support team

**Comment by Igor-Mochalin** [comment]
Ok, thanks  for  explanation!  One  more  issue: ( or maybe  by design )

I can't use  something  like this
localhost,{KDBBASEPORT}+25,segmentedchainedtickerplant,sctp .....    **-.sctp.tickerplantname stp1 stp2**

i.e .
 i would  like  to subscribe to 2 tps  from one  chain  tp ...
current  behavior:
subscription  works  fine  for stp1 
and  .stpps.subrequestall  is empty  for  stp2

**Comment by etennoQ** [comment]
At the minute, the SCTP doesn't support multiple subscriptions, however for a quick solution if you head to `code/segmentedtickerplant/sctp.q` and replace the subscribe function in there with the following:

    subscribe:{[]
      s:.sub.getsubscriptionhandles[`;tickerplantname;()!()];
      if[count s;
          subproc:flip s;
          `.sctp.tph set subproc`w;
          // get tickerplant date - default to today's date
          .lg.o[`subscribe;"subscribing to ", .Q.s1 subproc`procname];
          r:flip .sub.subscribe[subscribeto;subscribesyms;schema;replay;] each flip subproc;
          if[`d in key r;.u.d::r[`d]];
          if[(`icounts in key r) & (loggingmode<>`create); // dict r contains icounts & not using own logfile
            subtabs:$[subscribeto~`;key first r`icounts;subscribeto],();
            .u.jcounts::.u.icounts::$[0=count r`icounts;()!();subtabs!enlist [sum r`icounts]subtabs];
          ]
        ];
      }

This should allow multiple subscriptions with the config that you have. Note that some other features of the SCTP may not function as expected, though hopefully this is still of some use. I will pass on the feedback that this should be implemented properly.

Kindest regards
Support team

**Comment by mpotterq** [comment]
Hi @Igor-Mochalin , 

As an addendum to what @etennoQ has already said, the SCTP has been designed to be a replica of the main STP and for the relationship to be 1:1, so while it may be possible to get it to subscribe to multiple STPs, some of the more advanced functionality, like recovering from upstream logs, may not work as intended.

The good news is that if you just need a process which subscribes to multiple STPs and passes on updates, it is possible to throw something together in just a few lines of code:
```
// Example process which subscribes to multiple STPs and publishes the updates it receives

// Load in common code (including subscription code) and connect to all STPs
.proc.loadcommoncode:1b;
.servers.CONNECTIONS:`segmentedtickerplant;

// Set up connection management and subscribe to all STPs
init:{
  .servers.startup[];
  subs:.sub.getsubscriptionhandles[`segmentedtickerplant;`;()!()];
  subinfo::.sub.subscribe[`;`;1b;0b;] each subs;
 };

// Publish any updates it receives
upd:.stpps.pub;

// Run init function on startup
.proc.addinitlist(`init;`);
```
This process subscribes to all STPs and publishes any updates it receives to its subscribers, and is fairly simple to put together!

I hope this helps,

Kind Regards
Support Team

**Comment by Igor-Mochalin** [comment]
yes,  thanks  a lot!
