### ISSUE TITLE
pivot optional args do not work

### ISSUE THREAD

**Issue by korman5** [AquaQAnalytics/TorQ#387]
I had to change the first line of pivot function to be:

```q
checkargs[args;`table`by`piv`var`f`g;(" sS")]; / notice that f and g are missing in the code
```

and call the function with both f and g due to next code:

```q
if[not all `f`g in key args;  /could be more flexible if we check them separately 
```

**Comment by pkerrAqua** [comment]
Hello korman5, 

Thanks for bringing this to our attention, after some testing it appears there is an indexing issue when optinal arguments are used alongside the original code, as the original code only accounts for the dictionary keys to be `-table, -by, -piv, -var`

The issue will be continued to be investigated further and the code ammended as soon as possible to account for this error.
